# Site settings
title: jekyll-swagger
baseurl: "/jekyll-swagger" # the subpath of your site, e.g. /blog/
url: "http://jexhson.github.io/jekyll-swagger/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
